# Generated by Django 3.2.7 on 2021-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
